name: Build and test

on: [push]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Run dotnet test
      run: dotnet test
